name: Deploy static to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Crear config.js con TUS secrets del repo
      - name: Create runtime config
        run: |
          cat > config.js << 'EOF'
          window.__APP_CONFIG__ = {
            SUPABASE_URL: "${{ secrets.SUPABASE_URL }}",
            SUPABASE_ANON_KEY: "${{ secrets.SUPABASE_ANON_KEY }}",
            PASSWORD: "${{ secrets.PASSWORD }}",
            USE_MOCK: false
          };
          EOF

      # 2) Publicar todo el repo (carpeta raíz) a Pages
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .

  release:
    runs-on: ubuntu-latest
    needs: deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
